"""rename drop_date to exp_date

Revision ID: 3151451fa240
Revises: 3341c73ee7ca
Create Date: 2026-03-02 16:49:57.766244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3151451fa240'
down_revision: Union[str, None] = '3341c73ee7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('exp_date', sa.DateTime(), nullable=True))
    op.drop_column('links', 'drop_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('drop_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('links', 'exp_date')
    # ### end Alembic commands ###
