"""sync model

Revision ID: 3e4fbe2d6cd2
Revises: 3151451fa240
Create Date: 2026-03-03 15:45:53.402501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e4fbe2d6cd2'
down_revision: Union[str, None] = '3151451fa240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('short_code', sa.String(), nullable=False))
    op.add_column('links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_links_short_url', table_name='links')
    op.create_index(op.f('ix_links_short_code'), 'links', ['short_code'], unique=True)
    op.drop_column('links', 'short_url')
    op.drop_column('links', 'exp_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('exp_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_links_short_code'), table_name='links')
    op.create_index('ix_links_short_url', 'links', ['short_url'], unique=True)
    op.drop_column('links', 'expires_at')
    op.drop_column('links', 'short_code')
    # ### end Alembic commands ###
